### ISSUE TITLE
Gandi advice against?

### ISSUE THREAD

**Issue by falkn** [jasontbradshaw/gandi-dyndns#8]
Hi!

I wanted to use your nice little script, but when enabling the API to Gandi, they state that:
"It is strongly advised that you do not activate this feature if you use dynamic IP addresses." Do you have any background information about why they do this?
![gandi-api-notice](https://cloud.githubusercontent.com/assets/15221215/19417789/03d2d234-93b6-11e6-9d94-4999c726624c.png)

Kindest regards,
Christian

**Comment by jasontbradshaw** [comment]
This looks to be unrelated to using the API, and this script should work just fine without it. The Gandi UI is a bit confusing though, and I can see how this would look like it's part of it.

It appears to be a feature that allows you to restrict the APIs that you allow to access your account's API, though. If, for example, you had some servers on AWS that did things to your account on a regular basis, you could enable this feature and add in the IP address of those servers. This would prevent anyone else from accessing your account, even if they had the credentials for some reason. Essentially, it's a security feature.

It doesn't look like you have to enable it for API access to work, though, since it appears to be a separate feature. Instead, you should be able to click one of the other blue "submit" buttons above that and enable API access for your Gandi account as the README describes.
